set_property SRC_FILE_INFO {cfile:/media/tony/backup/pin-uart/vivado/targets/xilinx/my_artix_board/fpga.xdc rfile:../../../fpga.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E3 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A1 IOSTANDARD LVCMOS33} [get_ports PA1]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A13 IOSTANDARD LVCMOS33} [get_ports PA13]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A14 IOSTANDARD LVCMOS33} [get_ports PA14]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A15 IOSTANDARD LVCMOS33} [get_ports PA15]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A16 IOSTANDARD LVCMOS33} [get_ports PA16]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A18 IOSTANDARD LVCMOS33} [get_ports PA18]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A19 IOSTANDARD LVCMOS33} [get_ports PA19]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A20 IOSTANDARD LVCMOS33} [get_ports PA20]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A21 IOSTANDARD LVCMOS33} [get_ports PA21]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B1 IOSTANDARD LVCMOS33} [get_ports PB1]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B2 IOSTANDARD LVCMOS33} [get_ports PB2]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B13 IOSTANDARD LVCMOS33} [get_ports PB13]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B15 IOSTANDARD LVCMOS33} [get_ports PB15]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B16 IOSTANDARD LVCMOS33} [get_ports PB16]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B17 IOSTANDARD LVCMOS33} [get_ports PB17]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B18 IOSTANDARD LVCMOS33} [get_ports PB18]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B20 IOSTANDARD LVCMOS33} [get_ports PB20]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B21 IOSTANDARD LVCMOS33} [get_ports PB21]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B22 IOSTANDARD LVCMOS33} [get_ports PB22]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C2 IOSTANDARD LVCMOS33} [get_ports PC2]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C13 IOSTANDARD LVCMOS33} [get_ports PC13]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C14 IOSTANDARD LVCMOS33} [get_ports PC14]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C15 IOSTANDARD LVCMOS33} [get_ports PC15]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C17 IOSTANDARD LVCMOS33} [get_ports PC17]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C18 IOSTANDARD LVCMOS33} [get_ports PC18]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C19 IOSTANDARD LVCMOS33} [get_ports PC19]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C20 IOSTANDARD LVCMOS33} [get_ports PC20]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C22 IOSTANDARD LVCMOS33} [get_ports PC22]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D1 IOSTANDARD LVCMOS33} [get_ports PD1]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D2 IOSTANDARD LVCMOS33} [get_ports PD2]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D14 IOSTANDARD LVCMOS33} [get_ports PD14]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D15 IOSTANDARD LVCMOS33} [get_ports PD15]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D16 IOSTANDARD LVCMOS33} [get_ports PD16]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D17 IOSTANDARD LVCMOS33} [get_ports PD17]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D19 IOSTANDARD LVCMOS33} [get_ports PD19]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D20 IOSTANDARD LVCMOS33} [get_ports PD20]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D21 IOSTANDARD LVCMOS33} [get_ports PD21]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D22 IOSTANDARD LVCMOS33} [get_ports PD22]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E1 IOSTANDARD LVCMOS33} [get_ports PE1]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E2 IOSTANDARD LVCMOS33} [get_ports PE2]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E13 IOSTANDARD LVCMOS33} [get_ports PE13]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E14 IOSTANDARD LVCMOS33} [get_ports PE14]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E16 IOSTANDARD LVCMOS33} [get_ports PE16]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E17 IOSTANDARD LVCMOS33} [get_ports PE17]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E18 IOSTANDARD LVCMOS33} [get_ports PE18]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E19 IOSTANDARD LVCMOS33} [get_ports PE19]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E21 IOSTANDARD LVCMOS33} [get_ports PE21]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E22 IOSTANDARD LVCMOS33} [get_ports PE22]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F1 IOSTANDARD LVCMOS33} [get_ports PF1]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F3 IOSTANDARD LVCMOS33} [get_ports PF3]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F4 IOSTANDARD LVCMOS33} [get_ports PF4]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F13 IOSTANDARD LVCMOS33} [get_ports PF13]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F14 IOSTANDARD LVCMOS33} [get_ports PF14]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F15 IOSTANDARD LVCMOS33} [get_ports PF15]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F16 IOSTANDARD LVCMOS33} [get_ports PF16]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F18 IOSTANDARD LVCMOS33} [get_ports PF18]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F19 IOSTANDARD LVCMOS33} [get_ports PF19]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F20 IOSTANDARD LVCMOS33} [get_ports PF20]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F21 IOSTANDARD LVCMOS33} [get_ports PF21]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G1 IOSTANDARD LVCMOS33} [get_ports PG1]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G2 IOSTANDARD LVCMOS33} [get_ports PG2]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G3 IOSTANDARD LVCMOS33} [get_ports PG3]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G4 IOSTANDARD LVCMOS33} [get_ports PG4]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G13 IOSTANDARD LVCMOS33} [get_ports PG13]
